---
services:
  heimdall-ts:
    image: tailscale/tailscale:latest
    container_name: ${STACK_NAME}-ts
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - heimdall-ts-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  heimdall-app:
    image: traefik:v3.3
    container_name: ${STACK_NAME}-app
    command:
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
    network_mode: service:heimdall-ts
    depends_on:
      - heimdall-ts
    environment:
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - heimdall-letsencrypt:/letsencrypt
    restart: unless-stopped

  heimdall-cf:
    image: cloudflare/cloudflared:latest
    container_name: ${STACK_NAME}-cf
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    network_mode: service:heimdall-ts
    depends_on:
      - heimdall-app
    restart: unless-stopped

volumes:
  heimdall-ts-state:
    name: ${STACK_NAME}-state
    driver: local

  heimdall-letsencrypt:
    name: ${STACK_NAME}-letsencrypt
    driver: local